### ISSUE TITLE
I use the 1.3.0 version of the music mod but it doesn't work successfully in the server

### ISSUE THREAD

**Issue by STqingfengOwO** [SemmieDev/Disc-Jockey#12]

**Comment by kyrielie** [comment]
```
[13:17:39] [Thread-12/ERROR]: Uncaught exception in thread "Thread-12"
java.lang.NoSuchMethodError: 'void net.minecraft.class_634.method_52787(net.minecraft.class_2596)'
	at semmiedev.disc_jockey.SongPlayer.tickPlayback(SongPlayer.java:169) ~[transformed-mod-disc-jockey.i0:0/:?]
	at semmiedev.disc_jockey.SongPlayer.lambda$startPlaybackThread$0(SongPlayer.java:79) ~[transformed-mod-disc-jockey.i0:0/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

This is the error that I'm getting for 1.3.0
The mod did not work for me in singleplayer either. I was able to preview, tune, but not play.
~~I am using fabric and quilted fabric and a couple other performance mods like sodium.~~

Edit: I was using quilt loader and fabric api etc. and also viafabric on 1.20.1
I think there is just some conflict, but making a new instance with just a couple other mods using fabric loader on 1.20.2 worked. I will try to identify the source of the error.


The update seems like a wonderful upgrade— I really love the mod! Thanks for the update <3
