### ISSUE TITLE
please update 1.20.6

### ISSUE THREAD

**Issue by MCFurina** [SemmieDev/Disc-Jockey#23]
can't load in 1.20.6 Fabric 0.15.11
↓ is error info (chinese)
有不兼容的模组！ (Incompatible mods found!)
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
确定了一种可能的解决方法，这样做可能会解决你的问题：
	 - 将 模组 'Disc Jockey' (disc_jockey) 1.5.0 替换为与这一模组兼容的 任意版本：
		 - minecraft 1.20.6
更多信息：
	 - 模组 'Disc Jockey' (disc_jockey) 1.5.0 需要 'Minecraft' (minecraft) 的 1.20.5 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 需要 'Minecraft' (minecraft) 的 从 1.14-（含）到 1.16-（不含）的任意版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.14.4 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.15.2 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.16.5 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.17.1 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.18.2 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.19.4 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.20.1 版本，但已经安装了的版本 1.20.6 不对！
	 - 模组 'ViaFabric for 1.20.4' (viafabric-mc1204) 0.4.14+68-main 需要 'Minecraft' (minecraft) 的 1.20.3 版本 或 1.20.4 版本，但已经安装了的版本 1.20.6 不对！
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

**Comment by SemmieDev** [comment]
Mod has been updated to 1.20.6. Sorry that it took a while, forgot about 1.20.6 because it was a very small update.
